[package]
name = "auth_circuit"
type = "bin"
authors = [""]
compiler_version = ">=1.0.0"

[dependencies]
bls12_381 = { tag = "v0.1.0", git = "https://github.com/Explore-Beyond-Innovations/noir-bls-library" }
